version: '2'

services:
  db:
    environment:
      POSTGRES_DB: little_quiz_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  app:
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/little_quiz_db
      REDIS_URL: redis://redis
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"
volumes:
  postgres_data: