version: '2'

services:
  db:
    environment:
      POSTGRES_PASSWORD: thisthis
    restart: always
    image: postgres
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  app:
    environment:
      DATABASE_URL: postgres://postgres:thisthis@db/postgres
      REDIS_URL: redis://redis
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_MANAGEPY_COLLECTSTATIC: "on"
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"
volumes:
  .pg_data: