# Generated by Django 2.1.3 on 2018-11-26 01:09

from django.db import migrations

import datetime

from quizapp.models import Category


def prep_dev_state_quiz(apps, schema_editor):
    category = Category.objects.create(category_name='General', description='Catch All')

    quiz_1 = category.quiz_set.create(
        pub_date=datetime.datetime.now(),
        quiz_name='state_capitals',
        quiz_title='State Capitals',
        description='A state capitals quiz',
        instructions='Guess the state capitals',
    )

    tx_question = quiz_1.question_set.create(
        question_name='texas',
        question_text='What is the capital of Texas?',
    )

    az_question = quiz_1.question_set.create(
        question_name='arizona',
        question_text='What is the capital of Arizona?',
    )

    fl_question = quiz_1.question_set.create(
        question_name='florida',
        question_text='What is the capital of Florida?',
    )

    ca_question = quiz_1.question_set.create(
        question_name='california',
        question_text='What is the capital of California?',
    )

    tx_question.choice_set.create(
        choice_name='tx_austin',
        choice_text='Austin',
        is_correct=True,
    )

    tx_question.choice_set.create(
        choice_name='tx_houston',
        choice_text='Houston',
        is_correct=False,
    )

    az_question.choice_set.create(
        choice_name='az_phoenix',
        choice_text='Phoenix',
        is_correct=True,
    )

    az_question.choice_set.create(
        choice_name='az_flagstaff',
        choice_text='Flagstaff',
        is_correct=False,
    )

    fl_question.choice_set.create(
        choice_name='fl_miami',
        choice_text='Miami',
        is_correct=False,
    )

    fl_question.choice_set.create(
        choice_name='fl_tallahassee',
        choice_text='Tallahassee',
        is_correct=True,
    )

    ca_question.choice_set.create(
        question=4,
        choice_name='ca_los_angeles',
        choice_text='Los Angeles',
        is_correct=False,
    )

    ca_question.choice_set.create(
        question=4,
        choice_name='ca_sacramento',
        choice_text='Sacramento',
        is_correct=True,
    )


def prep_dev_soccer_quiz(apps, schema_editor):
    category = Category.objects.create(category_name='General', description='Catch All')

    quiz_1 = category.quiz_set.create(
        pub_date=datetime.datetime.now(),
        quiz_name='soccer',
        quiz_title='Soccer',
        description='A soccer quiz',
        instructions='Answer right!!!',
    )

    wcup_question = quiz_1.question_set.create(
        question_name='world_cup',
        question_text='Who won the 1958 World Cup?',
    )

    uswnt_question = quiz_1.question_set.create(
        question_name='uswnt',
        question_text='Who was the coach of the US Women\'s National Team in 2018?',
    )

    man_u_question = quiz_1.question_set.create(
        question_name='man_u',
        question_text='What league is Manchester United in?',
    )

    wcup_question.choice_set.create(
        choice_name='brazil_wcup',
        choice_text='Brazil',
        is_correct=True,
    )

    wcup_question.choice_set.create(
        choice_name='germany',
        choice_text='Germany',
        is_correct=False,
    )

    uswnt_question.choice_set.create(
        choice_name='bruce_uswnt',
        choice_text='Bruce Arena',
        is_correct=False,
    )

    uswnt_question.choice_set.create(
        choice_name='jill_ellis_uswnt',
        choice_text='Jill Ellis',
        is_correct=True,
    )

    man_u_question.choice_set.create(
        choice_name='la_liga_man_u',
        choice_text='La Liga',
        is_correct=False,
    )

    man_u_question.choice_set.create(
        choice_name='premier_man_u',
        choice_text='English Premier League',
        is_correct=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(prep_dev_state_quiz),
        migrations.RunPython(prep_dev_soccer_quiz),
    ]
